### ISSUE TITLE
Create wire-frame draft

### ISSUE THREAD

**Issue by Ivraj** [Ivraj/homebase#1]
Create an initial draft of the wire-frame for review.

**Comment by Ivraj** [comment]
Would you be free anytime tomorrow night to go over some of your thoughts for design? The wire-frame doesn't have to be done, but I'd like to just get an idea of what you're thinking of.

**Comment by Ivraj** [comment]
^ @reineydays , forgot to tag you in that previous comment.

**Comment by reineydays** [comment]
Add arrows for model, along with history spreadsheet  in separate model with arguments filled in. Also meet with menaka to discuss side bar.
